sources:
  contaminants:
    "CC Bacteria": "sources/contaminants/cc_bacteria.yml"
    "CC Viruses": "sources/contaminants/cc_viruses.yml"
    "CC Eukaryota": "sources/contaminants/cc_eukaryota.yml"
    # "Custom Contaminants 1": "path/contfile1.tsv"
    # "Custom Contaminants 2": "path/contfile2.tsv"
  references:
    "Human-Related": "sources/references/human-related.yml"
    "Skin": "sources/references/skin.yml"
    "Oral": "sources/references/oral.yml"
    # "Custom References 1": "path/reffile1.tsv"
    # "Custom References 2": "path/reffile2.tsv"
  
# samples:
#   controls:
#     "Positve Controls": "path/file1.tsv"
#     "Negative Controls": "path/file1.tsv"

external:
  mgnify: "sources/mgnify/taxa_counts_top10.tsv"
  decontam:
    threshold: 0.2 # [0-1]
    method: "frequency" # frequency, prevalence, combined
    # # frequency (default: use sum of counts)
    # frequency_file: "path/file1.txt"
    # frequency_metadata: "Field1"
    # # prevalence (default: use all controls)
    # prevalence_file: 
    #  - "path/file1.txt"
    #  - "path/file2.txt"
    # prevalence_metadata: 
    #  "Field1": "ValueA"
    #  "Field2": "ValueB"

