references:
  "Contaminants": "files/contaminants.yml"
  "Human-related": "files/human-related.yml" 

# controls:
#   "Negative Controls": "path/file1.tsv"
#   "Positve Controls": 
#     "Metadata_Field": 
#       - "Metadata_Value1"
#       - "Metadata_Value2"

external:
  mgnify: "files/mgnify5989.tsv"
  decontam:
    threshold: 0.1 # [0-1] P* hyperparameter
    method: "frequency" # frequency, prevalence, combined
    # # frequency (default: use sum of counts)
    # frequency_file: "path/file1.txt"
    # frequency_metadata: "Field1"
    # # prevalence (default: use all controls)
    # prevalence_file: 
    #  - "path/file1.txt"
    #  - "path/file2.txt"
    # prevalence_metadata: 
    #  "Field1": 
    #    - "ValueA"
    #    - "ValueB"
    #  "Field2":
    #    - "ValueC"

